// Importações de Veículos Elétricos (Novos/Destaques)
import mercedesImg from "../assets/mercedes-benz.jpeg";
import jeepImg from "../assets/Jeep-avenger.jpg";
import seres3Img from "../assets/seres-3.jpg";
import modelYImg from "../assets/tesla-model-y.jpg";
import leafImg from "../assets/nissan-leaf.jpg";
import etronGtImg from "../assets/audi-etron-gt.jpg";
import model3Img from "../assets/tesla-model-3.jpg";
import i4Img from "../assets/bmw-i4.jpg";
import ex30Img from "../assets/volvo-ex30.jpg";
import xc40Img from "../assets/volvo-xc40.jpg";
import ix1Img from "../assets/bmw-ix1.jpg";
import taycanImg from "../assets/porsche-taycan.jpg";
import icarImg from "../assets/caoa-chery-icar.jpg";
import ora03Img from "../assets/gwm-ora-03.jpg";
import dolphinMiniImg from "../assets/byd-dolphin-mini.jpg";
import ejs1Img from "../assets/jac-ejs1.jpg";
import yuanPlusImg from "../assets/byd-yuan-plus.jpg";
import dolphinImg from "../assets/byd-dolphin.jpg";

// Importações de Veículos a Combustão (Populares no Brasil)
import upImg from "../assets/vw-up.jpg";
import kwidImg from "../assets/renault-kwid.jpg";
import golImg from "../assets/vw-gol.jpg";
import sanderoImg from "../assets/renault-sandero.jpg";
import cretaImg from "../assets/hyundai-creta.jpg";
import kicksImg from "../assets/nissan-kicks.jpg";
import nivusImg from "../assets/vw-nivus.jpg";
import civicImg from "../assets/honda-civic.jpg";
import stradaImg from "../assets/fiat-strada.jpg";
import s10Img from "../assets/chevrolet-s10.jpg";
import dusterImg from "../assets/renault-duster.jpg";
import toroImg from "../assets/fiat-toro.jpg";
import trackerImg from "../assets/chevrolet-tracker.jpg";
import poloImg from "../assets/vw-polo.jpg";
import corollaImg from "../assets/toyota-corolla.jpg";
import hb20Img from "../assets/hyundai-hb20.jpg";
import tcrossImg from "../assets/vw-tcross.jpg";
import argoImg from "../assets/fiat-argo.jpg";
import hiluxImg from "../assets/toyota-hilux.jpg";
import compassImg from "../assets/jeep-compass.jpg";
import onixImg from "../assets/chevrolet-onix.jpg";

export const electricVehicles = [
  {
    id: "ev1",
    type: "eletrico",
    brand: "Mercedes-Benz",
    model: "EQE SUV",
    year: 2026,
    price: "R$ 729.900,00",
    priceNum: 729900,
    consumption: "18.9 kWh/100km",
    consumptionNum: 18.9,
    image: mercedesImg,
    category: "SUV",
    tags: ["SUV de luxo", "Autonomia 550km"],
  },
  {
    id: "ev2",
    type: "eletrico",
    brand: "JEEP",
    model: "AVENGER ALTITUDE",
    year: 2026,
    price: "R$ 119.990,00",
    priceNum: 1199900, // Nota: Verifique se este valor não deveria ser 119990
    consumption: "15,4 kWh/100km",
    consumptionNum: 15.4,
    image: jeepImg,
    category: "SUV",
    tags: ["SUV topo de linha", "Autonomia 400km"],
  },
  {
    id: "ev3",
    type: "eletrico",
    brand: "Seres",
    model: "Seres 3",
    year: 2026,
    price: "R$ 199.900",
    priceNum: 199900,
    consumption: "15.5 kWh/100km",
    consumptionNum: 15.5,
    image: seres3Img,
    category: "SUV",
    tags: ["SUV acessível", "Autonomia 405km"],
  },
  {
    id: "ev4",
    type: "eletrico",
    brand: "Tesla",
    model: "Model Y",
    year: 2026,
    price: "R$ 429.900",
    priceNum: 429900,
    consumption: "16.1 kWh/100km",
    consumptionNum: 16.1,
    image: modelYImg,
    category: "SUV",
    tags: ["SUV mais vendido", "Autonomia 533km"],
  },
  {
    id: "ev5",
    type: "eletrico",
    brand: "Nissan",
    model: "Leaf",
    year: 2026,
    price: "R$ 299.900",
    priceNum: 299900,
    consumption: "15.8 kWh/100km",
    consumptionNum: 15.8,
    image: leafImg,
    category: "Hatch",
    tags: ["Pioneiro", "Autonomia 385km"],
  },
  {
    id: "ev6",
    type: "eletrico",
    brand: "Audi",
    model: "e-tron GT",
    year: 2026,
    price: "R$ 899.900",
    priceNum: 899900,
    consumption: "19.8 kWh/100km",
    consumptionNum: 19.8,
    image: etronGtImg,
    category: "Sedan",
    tags: ["Gran Turismo", "Autonomia 488km"],
  },
  {
    id: "ev7",
    type: "eletrico",
    brand: "Tesla",
    model: "Model 3",
    year: 2026,
    price: "R$ 349.900",
    priceNum: 349900,
    consumption: "14.3 kWh/100km",
    consumptionNum: 14.3,
    image: model3Img,
    category: "Sedan",
    tags: ["Autonomia 602km", "Autopilot"],
  },
  {
    id: "ev8",
    type: "eletrico",
    brand: "BMW",
    model: "i4 eDrive40",
    year: 2026,
    price: "R$ 489.900",
    priceNum: 489900,
    consumption: "16.5 kWh/100km",
    consumptionNum: 16.5,
    image: i4Img,
    category: "Sedan",
    tags: ["Sedã esportivo", "Autonomia 590km"],
  },
  {
    id: "ev9",
    type: "eletrico",
    brand: "Volvo",
    model: "Volvo EX30",
    year: 2026,
    price: "R$ 249.900",
    priceNum: 249900,
    consumption: "15.2 kWh/100km",
    consumptionNum: 15.2,
    image: ex30Img,
    category: "SUV",
    tags: ["SUV compacto premium", "Autonomia 480km"],
  },
  {
    id: "ev10",
    type: "eletrico",
    brand: "Volvo",
    model: "XC40 Recharge",
    year: 2026,
    price: "R$ 389.900",
    priceNum: 389900,
    consumption: "18.5 kWh/100km",
    consumptionNum: 18.5,
    image: xc40Img,
    category: "SUV",
    tags: ["SUV premium", "Autonomia 400km"],
  },
  {
    id: "ev11",
    type: "eletrico",
    brand: "BMW",
    model: "iX1",
    year: 2026,
    price: "R$ 379.900",
    priceNum: 379900,
    consumption: "17.8 kWh/100km",
    consumptionNum: 17.8,
    image: ix1Img,
    category: "SUV",
    tags: ["SUV compacto", "Autonomia 440km"],
  },
  {
    id: "ev12",
    type: "eletrico",
    brand: "Porsche",
    model: "Taycan",
    year: 2026,
    price: "R$ 699.900",
    priceNum: 699900,
    consumption: "19.2 kWh/100km",
    consumptionNum: 19.2,
    image: taycanImg,
    category: "Sedan",
    tags: ["Superesportivo", "800V"],
  },
  {
    id: "ev13",
    type: "eletrico",
    brand: "Caoa Chery",
    model: "iCar",
    year: 2026,
    price: "R$ 169.900",
    priceNum: 169900,
    consumption: "14.2 kWh/100km",
    consumptionNum: 14.2,
    image: icarImg,
    category: "Sedan",
    tags: ["Montado no Brasil", "Sedan elétrico"],
  },
  {
    id: "ev14",
    type: "eletrico",
    brand: "GWM",
    model: "Ora 03",
    year: 2026,
    price: "R$ 139.900",
    priceNum: 139900,
    consumption: "13.8 kWh/100km",
    consumptionNum: 13.8,
    image: ora03Img,
    category: "Hatch",
    tags: ["Fabricado em Iracemápolis-SP", "Design moderno"],
  },
  {
    id: "ev15",
    type: "eletrico",
    brand: "BYD",
    model: "Dolphin Mini",
    year: 2026,
    price: "R$ 119.800",
    priceNum: 119800,
    consumption: "12.9 kWh/100km",
    consumptionNum: 12.9,
    image: dolphinMiniImg,
    category: "Hatch",
    tags: ["Fabricado em Camaçari-BA", "Bateria Blade"],
  },
  {
    id: "ev16",
    type: "eletrico",
    brand: "JAC",
    model: "e-JS1",
    year: 2026,
    price: "R$ 155.900",
    priceNum: 155900,
    consumption: "13.5 kWh/100km",
    consumptionNum: 13.5,
    image: ejs1Img,
    category: "SUV",
    tags: ["Montado no Brasil", "SUV compacto"],
  },
  {
    id: "ev17",
    type: "eletrico",
    brand: "BYD",
    model: "Yuan Plus",
    year: 2026,
    price: "R$ 189.900",
    priceNum: 189900,
    consumption: "14.5 kWh/100km",
    consumptionNum: 14.5,
    image: yuanPlusImg,
    category: "SUV",
    tags: ["Fabricado em Camaçari-BA", "SUV Compacto"],
  },
  {
    id: "ev18",
    type: "eletrico",
    brand: "BYD",
    model: "Dolphin",
    year: 2026,
    price: "R$ 149.800",
    priceNum: 149800,
    consumption: "13.2 kWh/100km",
    consumptionNum: 13.2,
    image: dolphinImg,
    category: "Hatch",
    tags: ["Fabricado em Camaçari-BA", "Autonomia 450km"],
  }
];

export const combustionVehicles = [
  {
    id: "cv1",
    type: "combustao",
    brand: "Volkswagen",
    model: "UP",
    year: 2026,
    price: "R$ 63.000",
    priceNum: 63000,
    consumption: "12.9 L/100km",
    consumptionNum: 12.9,
    image: upImg,
    category: "Hatch",
    tags: ["Compacto", "Confortável"],
  },
  {
    id: "cv2",
    type: "combustao",
    brand: "Renault",
    model: "Kwid 1.0",
    year: 2026,
    price: "R$ 67.490",
    priceNum: 67490,
    consumption: "13.5 L/100km",
    consumptionNum: 13.5,
    image: kwidImg,
    category: "Hatch",
    tags: ["Mais barato", "Compacto"],
  },
  {
    id: "cv3",
    type: "combustao",
    brand: "Volkswagen",
    model: "Gol 1.0",
    year: 2026,
    price: "R$ 72.990",
    priceNum: 72990,
    consumption: "12.7 L/100km",
    consumptionNum: 12.7,
    image: golImg,
    category: "Hatch",
    tags: ["Clássico brasileiro", "Confiável"],
  },
  {
    id: "cv4",
    type: "combustao",
    brand: "Renault",
    model: "Sandero 1.0",
    year: 2026,
    price: "R$ 79.990",
    priceNum: 79990,
    consumption: "12.3 L/100km",
    consumptionNum: 12.3,
    image: sanderoImg,
    category: "Hatch",
    tags: ["Espaçoso", "Custo-benefício"],
  },
  {
    id: "cv5",
    type: "combustao",
    brand: "Hyundai",
    model: "Creta 1.0 Turbo",
    year: 2026,
    price: "R$ 139.990",
    priceNum: 139990,
    consumption: "11.6 L/100km",
    consumptionNum: 11.6,
    image: cretaImg,
    category: "SUV",
    tags: ["Líder de vendas SUV", "Completo"],
  },
  {
    id: "cv6",
    type: "combustao",
    brand: "Nissan",
    model: "Kicks 1.6",
    year: 2026,
    price: "R$ 119.990",
    priceNum: 119990,
    consumption: "11.8 L/100km",
    consumptionNum: 11.8,
    image: kicksImg,
    category: "SUV",
    tags: ["SUV urbano", "Espaço interno"],
  },
  {
    id: "cv7",
    type: "combustao",
    brand: "Volkswagen",
    model: "Nivus 1.0 TSI",
    year: 2026,
    price: "R$ 119.990",
    priceNum: 119990,
    consumption: "12.4 L/100km",
    consumptionNum: 12.4,
    image: nivusImg,
    category: "SUV",
    tags: ["SUV cupê", "Design único"],
  },
  {
    id: "cv8",
    type: "combustao",
    brand: "Honda",
    model: "Civic 2.0",
    year: 2026,
    price: "R$ 189.990",
    priceNum: 189990,
    consumption: "11.2 L/100km",
    consumptionNum: 11.2,
    image: civicImg,
    category: "Sedan",
    tags: ["Sedã premium", "Esportivo"],
  },
  {
    id: "cv9",
    type: "combustao",
    brand: "Fiat",
    model: "Strada Endurance",
    year: 2026,
    price: "R$ 94.990",
    priceNum: 94990,
    consumption: "12.1 L/100km",
    consumptionNum: 12.1,
    image: stradaImg,
    category: "Pickup",
    tags: ["Pickup compacta", "Mais vendida"],
  },
  {
    id: "cv10",
    type: "combustao",
    brand: "Chevrolet",
    model: "S10 2.8 Diesel",
    year: 2026,
    price: "R$ 239.990",
    priceNum: 239990,
    consumption: "9.8 L/100km",
    consumptionNum: 9.8,
    image: s10Img,
    category: "Pickup",
    tags: ["Pickup média", "Motor diesel"],
  },
  {
    id: "cv11",
    type: "combustao",
    brand: "Renault",
    model: "Duster 1.6",
    year: 2026,
    price: "R$ 129.990",
    priceNum: 129990,
    consumption: "11.4 L/100km",
    consumptionNum: 11.4,
    image: dusterImg,
    category: "SUV",
    tags: ["SUV robusto", "4x4 opcional"],
  },
  {
    id: "cv12",
    type: "combustao",
    brand: "Fiat",
    model: "Toro 2.0 Diesel",
    year: 2026,
    price: "R$ 179.990",
    priceNum: 179990,
    consumption: "9.5 L/100km",
    consumptionNum: 9.5,
    image: toroImg,
    category: "Pickup",
    tags: ["Pickup média", "Motor diesel"],
  },
  {
    id: "cv13",
    type: "combustao",
    brand: "Chevrolet",
    model: "Tracker 1.0 Turbo",
    year: 2026,
    price: "R$ 139.990",
    priceNum: 139990,
    consumption: "11.7 L/100km",
    consumptionNum: 11.7,
    image: trackerImg,
    category: "SUV",
    tags: ["SUV popular", "Econômico"],
  },
  {
    id: "cv14",
    type: "combustao",
    brand: "Volkswagen",
    model: "Polo 1.0 TSI",
    year: 2026,
    price: "R$ 95.990",
    priceNum: 95990,
    consumption: "12.8 L/100km",
    consumptionNum: 12.8,
    image: poloImg,
    category: "Hatch",
    tags: ["Premium", "Tecnologia VW"],
  },
  {
    id: "cv15",
    type: "combustao",
    brand: "Toyota",
    model: "Corolla 2.0",
    year: 2026,
    price: "R$ 145.990",
    priceNum: 145990,
    consumption: "11.5 L/100km",
    consumptionNum: 11.5,
    image: corollaImg,
    category: "Sedan",
    tags: ["Sedã médio", "Híbrido flex"],
  },
  {
    id: "cv16",
    type: "combustao",
    brand: "Hyundai",
    model: "HB20 1.0",
    year: 2026,
    price: "R$ 82.490",
    priceNum: 82490,
    consumption: "12.2 L/100km",
    consumptionNum: 12.2,
    image: hb20Img,
    category: "Hatch",
    tags: ["Confiável", "Garantia 5 anos"],
  },
  {
    id: "cv17",
    type: "combustao",
    brand: "Volkswagen",
    model: "T-Cross 1.0 TSI",
    year: 2026,
    price: "R$ 149.990",
    priceNum: 149990,
    consumption: "11.9 L/100km",
    consumptionNum: 11.9,
    image: tcrossImg,
    category: "SUV",
    tags: ["SUV compacto", "Porta-malas grande"],
  },
  {
    id: "cv18",
    type: "combustao",
    brand: "Fiat",
    model: "Argo 1.0",
    year: 2026,
    price: "R$ 78.990",
    priceNum: 78990,
    consumption: "11.8 L/100km",
    consumptionNum: 11.8,
    image: argoImg,
    category: "Hatch",
    tags: ["Mais vendido", "Econômico"],
  },
  {
    id: "cv19",
    type: "combustao",
    brand: "Toyota",
    model: "Hilux 2.8 Diesel",
    year: 2026,
    price: "R$ 289.990",
    priceNum: 289990,
    consumption: "10.2 L/100km",
    consumptionNum: 10.2,
    image: hiluxImg,
    category: "Pickup",
    tags: ["Pickup grande", "Indestrutível"],
  },
  {
    id: "cv20",
    type: "combustao",
    brand: "Jeep",
    model: "Compass 1.3 Turbo",
    year: 2026,
    price: "R$ 169.990",
    priceNum: 169990,
    consumption: "10.8 L/100km",
    consumptionNum: 10.8,
    image: compassImg,
    category: "SUV",
    tags: ["SUV médio", "4x4"],
  },
  {
    id: "cv21",
    type: "combustao",
    brand: "Chevrolet",
    model: "Onix 1.0 Turbo",
    year: 2026,
    price: "R$ 89.990",
    priceNum: 89990,
    consumption: "12.5 L/100km",
    consumptionNum: 12.5,
    image: onixImg,
    category: "Hatch",
    tags: ["Popular", "Motor turbo"],
  },
];

export const allVehicles = [...electricVehicles, ...combustionVehicles];
export const categories = ["Todos", "Hatch", "Sedan", "SUV", "Pickup"];